{% set name = "blpapi" %}
{% set version = "3.12.2" %}
{% set version_sha = "d6676adcfb2e8e9fd3a485525b7efd5634cec94d783bdfe3d3f49e3fa31b4a4e" %}
{% set blpapicpp_linux_version = "3.12.2.1" %}
{% set blpapicpp_win_version = "3.12.2.1" %}
{% set blpapicpp_linux_sha = "444742150ed4420ffe48322838487d7dc11d07409c9056e0f6fd83e239589922" %}
{% set blpapicpp_win_sha = "3123b5d2592ccc6f8bdf969204afae3c2af1b02d1e1e95c8275b02e48a00fc8a" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://bloomberg.bintray.com/pip/simple/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ version_sha }}
  - url: https://bloomberg.bintray.com/BLPAPI-Experimental-Generic/blpapi_cpp_3.12.2.1-linux.tar.gz  # [linux]
    sha256: {{ blpapicpp_linux_sha }}  # [linux]
  - url: https://software.tech.bloomberg/BLPAPI-Experimental-Generic/blpapi_cpp_{{ blpapicpp_win_version }}-windows.zip  # [win]
    sha256: {{ blpapicpp_win_sha }}  # [win]

build:
  number: 1
  skip: true  # [osx]
  string: py{{ CONDA_PY }}_blpapicpp{{ blpapicpp_linux_version }}_{{ PKG_BUILDNUM }}  # [linux]
  string: py{{ CONDA_PY }}_blpapicpp{{ blpapicpp_win_version }}_{{ PKG_BUILDNUM }}  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - blpapi

about:
  home: https://www.bloomberg.com/professional/support/api-library/
  license: Copyright 2012. Bloomberg Finance L.P.
  license_file: License.txt
  summary: 'Python SDK for Bloomberg BLPAPI (<=3.9)'

extra:
  recipe-maintainers:
    - matthewgilbert
