{% set name = "blpapi" %}
{% set version = "3.20.1" %}
{% set blpapicpp_linux_version = "3.19.1.1" %}
{% set blpapicpp_win_version = "3.19.1.1" %}
{% set blpapicpp_osx_version = "3.19.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://bcms.bloomberg.com/pip/simple/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: e955dd9d218411affb50fd58e10dc140b137baf4ef1e58146c0763ef99b4749d
  - url: https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_{{ blpapicpp_linux_version }}-linux.tar.gz  # [linux]
    sha256: d68ffe4e30a6dcc37a1884013dc67312802b1bdd7a4886ead5ac783bcfb1f180  # [linux]
  - url: https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_{{ blpapicpp_win_version }}-windows.zip  # [win]
    sha256: 55eea42d5587df52c39157ba9285c41f2cf4034d7fc614244cd1e58c9297d308  # [win]
  - url: https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_{{ blpapicpp_osx_version }}-macos.tar.gz  # [osx]
    sha256: d6d23831db85a674a0d647d2d2deac3e9aa9ada699e1588ab5f128d453e185ba  # [osx]
  - url: https://bcms.bloomberg.com/pip/simple/{{ name }}/{{ name }}-{{ version }}-cp39-cp39-macosx_10_9_x86_64.whl  # [osx]
    sha256: 17cda7dd9bc77275aa3578e8426b3ca2dfecbf1b5b97776b65218bf5266828b1  # [osx]
  - url: https://bcms.bloomberg.com/pip/simple/{{ name }}/{{ name }}-{{ version }}-cp310-cp310-macosx_10_9_universal2.whl  # [osx]
    sha256: b491d7a793ccc892498b18f9f0706a15e953bf49613106930fe17e0987439db8  # [osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - blpapi

about:
  home: https://www.bloomberg.com/professional/support/api-library/
  license: Copyright 2012. Bloomberg Finance L.P.
  license_file: License.txt
  summary: Python SDK for Bloomberg BLPAPI (<=3.9)

extra:
  recipe-maintainers:
    - reggied
    - matthewgilbert
