{% set name = "blpapi" %}
{% set version = "3.16.2" %}
{% set blpapicpp_linux_version = "3.16.1.1" %}
{% set blpapicpp_win_version = "3.16.1.1" %}
{% set blpapicpp_osx_version = "3.16.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://bcms.bloomberg.com/pip/simple/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ffcb9c3ff198fbf3c4ae44c7f6be10e768a1af66818c2881e2b430e7e1be3ed6
  - url: https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_{{ blpapicpp_linux_version }}-linux.tar.gz  # [linux]
    sha256: d8e0db4b4754f725c052084c09c07e3d111f655fd7079762f23ecc05d6402afd  # [linux]
  - url: https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_{{ blpapicpp_win_version }}-windows.zip  # [win]
    sha256: 82c3935a83487b8f3bbe3b3d0bb5d56abbd36b4461f8141ff1e42a746414979c  # [win]
  - url: https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_{{ blpapicpp_osx_version }}-macos.tar.gz  # [osx]
    sha256: e99ad9dea748755d3abfcce5cbd1a076e7ee5d9da7b12ca7d718e6801026bf68  # [osx]

build:
  number: 1
  string: py{{ CONDA_PY }}_blpapicpp{{ blpapicpp_linux_version }}_{{ PKG_BUILDNUM }}  # [linux]
  string: py{{ CONDA_PY }}_blpapicpp{{ blpapicpp_win_version }}_{{ PKG_BUILDNUM }}  # [win]
  string: py{{ CONDA_PY }}_blpapicpp{{ blpapicpp_osx_version }}_{{ PKG_BUILDNUM }}  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - blpapi

about:
  home: https://www.bloomberg.com/professional/support/api-library/
  license: Copyright 2012. Bloomberg Finance L.P.
  license_file: License.txt
  summary: 'Python SDK for Bloomberg BLPAPI (<=3.9)'

extra:
  recipe-maintainers:
    - matthewgilbert
