{% set name = "blpapi" %}
{% set version = "3.24.4" %}
{% set blpapicpp_linux_version = "3.24.4.1" %}
{% set blpapicpp_win_version = "3.24.4.1" %}
{% set blpapicpp_osx_version = "3.24.4.1" %}
{% set blpapicpp_osx_arm64_version = "3.24.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://blpapi.bloomberg.com/repository/releases/python/{{ name }}-{{ version }}.tar.gz
    sha256: 77a88addb073df647e615a76bdb0df91feb6003511efed2376087a8bab75b5e7
  - url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_{{ blpapicpp_linux_version }}-linux.tar.gz  # [linux]
    sha256: c2949dcc83831460271e969048abd9703e01eb27a67308f3a039816be2f439db    # [linux]
  - url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_{{ blpapicpp_win_version }}-windows.zip  # [win]
    sha256: cef04c60afb872b9c9b000254d5ee22d56a8d66fa3454c0636e705c1aa7041a4    # [win]
  - url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_{{ blpapicpp_osx_version }}-macos-arm64.tar.gz  # [osx and arm64]
    sha256: 55453a13f43f564f003a654ac20dda3f30c2d4edc8fc9cf943f5b9ce3a928776    # [osx and arm64]

build:
  number: 1
  skip: true  # [osx and x86_64]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
test:
  imports:
    - blpapi

about:
  home: https://www.bloomberg.com/professional/support/api-library/
  license: LicenseRef-Bloomberg-BLPAPI
  license_file: License.txt
  summary: Python SDK for Bloomberg BLPAPI

extra:
  recipe-maintainers:
    - reggied
    - matthewgilbert
    - adament
