{% set name = "blpapi" %}
{% set version = "3.21.0" %}
{% set blpapicpp_linux_version = "3.21.0.1" %}
{% set blpapicpp_win_version = "3.21.0.1" %}
{% set blpapicpp_osx_version = "3.21.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://bcms.bloomberg.com/pip/simple/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 6e9034cc8ad976615a49e2e4694cd1948e90a91438f842c8a7e2e01073470aba
  - url: https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_{{ blpapicpp_linux_version }}-linux.tar.gz  # [linux]
    sha256: 456123d318577b983ed5290c17b613a1088e17dba0b6652143f3041dd445c509    # [linux]
  - url: https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_{{ blpapicpp_win_version }}-windows.zip  # [win]
    sha256: 4976c859ecef574c3cd9a656677f180c97493efb6df98a2f18f04c34894d5943    # [win]
  - url: https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_{{ blpapicpp_osx_version }}-macos.tar.gz  # [osx]
    sha256: eaf9f3e5caede1655277d19d5f78d9f2c5a6d9f922056eef323fe57d3a9734ee    # [osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - blpapi

about:
  home: https://www.bloomberg.com/professional/support/api-library/
  license: Copyright 2012. Bloomberg Finance L.P.
  license_file: License.txt
  summary: Python SDK for Bloomberg BLPAPI (<=3.9)

extra:
  recipe-maintainers:
    - reggied
    - matthewgilbert
