context:
  name: blpapi
  version: "3.25.7.1"
  blpapicpp_linux_version: ${{ version }}
  blpapicpp_win_version: ${{ version }}
  blpapicpp_osx_version: ${{ version }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://blpapi.bloomberg.com/repository/releases/python/${{ name }}-${{ version }}.tar.gz
    sha256: 845dab573e7bfed7a2c53a52a4e45815ae51f623e04dd92eb8aed032340ee9bc
  - if: linux
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_linux_version }}-linux.tar.gz
      sha256: 3144e010a9e76dc750a9806212d309554a93d8c2a1e23d0c7ac882739db8af19
      target_directory: blpapi
  - if: win
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_win_version }}-windows.zip
      sha256: 0542884d2738d17ee10118615e686509872f565f1a26f0de04b3666251f6f8e7
      target_directory: blpapi
  - if: osx and arm64
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_osx_version }}-macos-arm64.tar.gz
      sha256: e7d60267b104907e2ca08669863884307ca06f6c647e62a6d85f08cded8dccfd
      target_directory: blpapi

build:
  number: 1
  skip: osx and x86_64

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - blpapi

about:
  license: LicenseRef-Bloomberg-BLPAPI
  license_file: License.txt
  summary: Python SDK for Bloomberg BLPAPI
  homepage: https://www.bloomberg.com/professional/support/api-library/

extra:
  recipe-maintainers:
    - reggied
    - matthewgilbert
    - adament
