context:
  name: blpapi
  version: "3.25.10.1"
  blpapicpp_linux_version: ${{ version }}
  blpapicpp_win_version: ${{ version }}
  blpapicpp_osx_version: ${{ version }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://blpapi.bloomberg.com/repository/releases/python/${{ name }}-${{ version }}.tar.gz
    sha256: cdeddc0ef4571f3133161a00fcb224935f285a1912cb133e4abc0f274c53f011
  - if: linux
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_linux_version }}-linux.tar.gz
      sha256: a8786b2e019fdfd5c138719b64c7a8198d67546ae0533ecb846b7d7c2978622f
      target_directory: blpapi
  - if: win
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_win_version }}-windows.zip
      sha256: 681eb7fc7cafaa1dbbb22256d5412910e86be66abe57f18555b4ec2990624fae
      target_directory: blpapi
  - if: osx and arm64
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_osx_version }}-macos-arm64.tar.gz
      sha256: fef2fe694c4a364f79a5dddb04385966953c347bc8e32e6e3f1e17429cbee2e3
      target_directory: blpapi

build:
  number: 0
  skip: osx and x86_64

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - blpapi

about:
  license: LicenseRef-Bloomberg-BLPAPI
  license_file: License.txt
  summary: Python SDK for Bloomberg BLPAPI
  homepage: https://www.bloomberg.com/professional/support/api-library/

extra:
  recipe-maintainers:
    - reggied
    - matthewgilbert
    - adament
