context:
  name: blpapi
  version: "3.26.1.1"
  blpapicpp_linux_version: ${{ version }}
  blpapicpp_win_version: ${{ version }}
  blpapicpp_osx_version: ${{ version }}

recipe:
  name: blpapi-split
  version: ${{ version }}

source:
  - url: https://blpapi.bloomberg.com/repository/releases/python/${{ name }}-${{ version }}.tar.gz
    sha256: 844eed5a8246ed2ab1910a204fe3a0e6a9a4878e0c4d8c97ba9bbd67acb0ea6b
  - if: linux
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_linux_version }}-linux.tar.gz
      sha256: 6f1e525de1094def3e29488c06e89b24b30c409120b4faecda5e38557a5f5251
      target_directory: blpapi
  - if: win
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_win_version }}-windows.zip
      sha256: 5bca864d38d43e02a67eb480287e90ed9472b8e0b8728060644bfec3027d5f76
      target_directory: blpapi
  - if: osx and arm64
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_osx_version }}-macos-arm64.tar.gz
      sha256: 8d2517338a9ad5c003f93469da8619a335f9bb1f652c78cf7e3fe18ab507a6c8
      target_directory: blpapi

build:
  number: 0
  skip: osx and x86_64

outputs:
  - package:
      name: libblpapi
      version: ${{ version }}
    build:
      script:
        - if: unix
          then: build-lib.sh
          else: build-lib.bat
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
      run_exports:
        - ${{ pin_subpackage('libblpapi', upper_bound='x.x.x.x') }}
    tests:
      - script:
          - if: unix
            then:
              - test -f $PREFIX/lib/libblpapi3_64.so || test -f $PREFIX/lib/libblpapi3_64.dylib
            else:
              - if exist %LIBRARY_PREFIX%\bin\blpapi3_64.dll (exit 0) else (exit 1)

  - package:
      name: libblpapi-devel
      version: ${{ version }}
    build:
      script:
        - if: unix
          then: build-devel.sh
          else: build-devel.bat
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
      host:
        - ${{ pin_subpackage('libblpapi', exact=True) }}
      run:
        - ${{ pin_subpackage('libblpapi', exact=True) }}
    tests:
      - script:
          - if: unix
            then:
              - test -f $PREFIX/include/blpapi_session.h
              - test -d $PREFIX/lib/cmake/blpapi || true
            else:
              - if exist %LIBRARY_PREFIX%\include\blpapi_session.h (exit 0) else (exit 1)

  - package:
      name: blpapi
      version: ${{ version }}
    build:
      script:
        - if: unix
          then: build-py.sh
          else: build-py.bat
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
      host:
        - python
        - setuptools
        - pip
        - ${{ pin_subpackage('libblpapi-devel', exact=True) }}
      run:
        - python
        - ${{ pin_subpackage('libblpapi', exact=True) }}
    tests:
      - python:
          imports:
            - blpapi
          pip_check: false

about:
  license: LicenseRef-Bloomberg-BLPAPI
  license_file: License.txt
  summary: Python SDK for Bloomberg BLPAPI
  homepage: https://www.bloomberg.com/professional/support/api-library/

extra:
  recipe-maintainers:
    - reggied
    - matthewgilbert
    - adament
    - benmoss
