context:
  name: blpapi
  version: "3.25.5.1"
  blpapicpp_linux_version: ${{ version }}
  blpapicpp_win_version: ${{ version }}
  blpapicpp_osx_version: ${{ version }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://blpapi.bloomberg.com/repository/releases/python/${{ name }}-${{ version }}.tar.gz
    sha256: ff2409bfb9ee90530f115fece3c03ec0b83c99fe2c383bfbf630e29bc5910ca0
  - if: linux
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_linux_version }}-linux.tar.gz
      sha256: 83f3efd9884eedb17636c5a402f65a0e800b09c9520a3ce8fe3d3c9cdab42151
      target_directory: blpapi
  - if: win
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_win_version }}-windows.zip
      sha256: 4408aca8ec26f3775d1e46ba05e0984dd836fb13eb81dc20aa79083e460d7b07
      target_directory: blpapi
  - if: osx and arm64
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_osx_version }}-macos-arm64.tar.gz
      sha256: 2d4caa86b27d9ab17adcff9fdae48ce559e04f75bd927ff9efec7fd5a975bf10
      target_directory: blpapi

build:
  number: 0
  skip: osx and x86_64

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - blpapi

about:
  license: LicenseRef-Bloomberg-BLPAPI
  license_file: License.txt
  summary: Python SDK for Bloomberg BLPAPI
  homepage: https://www.bloomberg.com/professional/support/api-library/

extra:
  recipe-maintainers:
    - reggied
    - matthewgilbert
    - adament
