context:
  name: blpapi
  version: "3.26.5.1"
  blpapicpp_linux_version: ${{ version }}
  blpapicpp_win_version: ${{ version }}
  blpapicpp_osx_version: ${{ version }}

recipe:
  name: blpapi-split
  version: ${{ version }}

source:
  - url: https://blpapi.bloomberg.com/repository/releases/python/${{ name }}-${{ version }}.tar.gz
    sha256: 7d880f315d0c70c72129329a48f584a1681e64a6546a6bb0ceab78c399cbb0b3
  - if: linux
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_linux_version }}-linux.tar.gz
      sha256: a91cc23a02a469115de88d72c5001a0d5eb0c1076b9ea7300c352c7dbb7d8443
      target_directory: blpapi
  - if: win
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_win_version }}-windows.zip
      sha256: 4547a7daf8174e2024ef7150e909b5b8c43b963e2c99c9bf839eaceeeb403873
      target_directory: blpapi
  - if: osx and arm64
    then:
      url: https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_${{ blpapicpp_osx_version }}-macos-arm64.tar.gz
      sha256: d46f086f3ac8e17ccc7762e9f5c0c2929370269dd1819110bd00187194f97cc0
      target_directory: blpapi

build:
  number: 0
  skip: osx and x86_64

outputs:
  - package:
      name: libblpapi
      version: ${{ version }}
    build:
      script:
        - if: unix
          then: build-lib.sh
          else: build-lib.bat
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
      run_exports:
        - ${{ pin_subpackage('libblpapi', upper_bound='x.x.x.x') }}
    tests:
      - script:
          - if: unix
            then:
              - test -f $PREFIX/lib/libblpapi3_64.so || test -f $PREFIX/lib/libblpapi3_64.dylib
            else:
              - if exist %LIBRARY_PREFIX%\bin\blpapi3_64.dll (exit 0) else (exit 1)

  - package:
      name: libblpapi-devel
      version: ${{ version }}
    build:
      script:
        - if: unix
          then: build-devel.sh
          else: build-devel.bat
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
      host:
        - ${{ pin_subpackage('libblpapi', exact=True) }}
      run:
        - ${{ pin_subpackage('libblpapi', exact=True) }}
    tests:
      - script:
          - if: unix
            then:
              - test -f $PREFIX/include/blpapi_session.h
              - test -d $PREFIX/lib/cmake/blpapi || true
            else:
              - if exist %LIBRARY_PREFIX%\include\blpapi_session.h (exit 0) else (exit 1)
              - if exist %LIBRARY_PREFIX%\lib\blpapi3_64.lib (exit 0) else (exit 1)

  - package:
      name: blpapi
      version: ${{ version }}
    build:
      script:
        - if: unix
          then: build-py.sh
          else: build-py.bat
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
      host:
        - python
        - setuptools
        - pip
        - ${{ pin_subpackage('libblpapi-devel', exact=True) }}
      run:
        - python
        - ${{ pin_subpackage('libblpapi', exact=True) }}
    tests:
      - python:
          imports:
            - blpapi
          pip_check: false

about:
  license: LicenseRef-Bloomberg-BLPAPI
  license_file: License.txt
  summary: Python SDK for Bloomberg BLPAPI
  homepage: https://www.bloomberg.com/professional/support/api-library/

extra:
  recipe-maintainers:
    - reggied
    - matthewgilbert
    - adament
    - benmoss
