appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bTVt37F9vAMkLhT0z0T0msFF7WlLcFScG8l2muDBsfxNwbVsNxnQ9jCxnUN6+RxZXnBtMBmVLlmUlnzlGcKT3SThfFLZ5o83UFUD9pSikHK0nXRzoQNWeTrFv3/pstJ1uRC8gvsfOlgLwGdqOVD6CB1Y81wrXo8ICsX4ClEFzPa+oHVbeiO62Loyt7SaPE4wVY31MS15GFhvZvidkV02MjLLP4w64CW3QGxVeIvyoN2QDL3jVaw57ycwxwqU0dyJDwVdlkMca3+s1v92AAXII1TvGpx4ukzd9/yfxzAYBQqYPCkULV5HTJEN7Zp8a189OSWodaT0a36/kFt7s1HyJ5mlro4sbFZqFBnh9fQezrImKIFEL4gM4r2dXVSI0qHgFZWGq4idJKdJhmvxHd+H3SpuY50LVCfYLM+L8At5V/d2GuYAv1ahqG3Wvj7tLNfyamxZRe1hwynVNT3HLJfTwZZPEU7xeKGF1LyYyTIqGnPoTubEZ34XN22QNh4tIpHrYOBtEZA1FZaVWhXpoc0mTTcBocMtjocrEHQ1quWatItWaVbGU1svQp2AEahn1J+/Nhlmk7e9ppB7XaIqFzWBm1oiQCvD+jcfecmCz9fzbq94baw7rJcQh2OXR0wqkD2M7ACHo/lzhPTTVhfOeqy3HX9Mcn0s7PegGBhwAb8hrnk=}
